apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.application.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.application.name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
